### ISSUE TITLE
Using  query builder  in service implementation

### ISSUE THREAD

**Issue by bionner** [yajra/laravel-datatables#1755]
Hi. I builded a 3 union table query with query builder. I need to filter the first union applying a group by, to sums the quantity field. The method mergeBindings accepts a querybuilder instead eloquent, then i had to build all my query with Query Builder. I found this approach, but i hope you have one to resolve it with Eloquent.
The error on render is as follows:

(1/1) BadMethodCallExceptionMethod getQuery does not exist.
--
in Macroable.php (line 74)
at Collection->__call('getQuery', array())in EloquentEngine.php (line 39)
at Collection->getQuery()in EloquentEngine.php (line 39)
at EloquentEngine->__construct(object(Collection), object(Request))in Datatables.php (line 97)
at Datatables->eloquent(object(Collection))in ProductoReporteDataTable.php (line 19)
at ProductoReporteDataTable->ajax()in DataTable.php (line 120)

` public function query()
    {

        $marca = $this->request()->get('marca');
        $categoria = $this->request()->get('categoria');
        /* $from = $this->request()->get('from');
        $to = $this->request()->get('to'); */

        $from = '2018-01-01';
        $to = '2018-01-31';

        $productos =
            DB::table('producto')
            ->select(
                'producto.id_producto',
                'producto.nombre',
                'marca.descripcion as marca',
                'color.descripcion as color',
                'categoria.descripcion as categoria',
                'venta_detalle_producto.cantidad'
            )
            ->join('marca', 'producto.id_marca', '=', 'marca.id_marca')
            ->join('color', 'producto.id_color', '=', 'color.id_color', 'left outer')
            ->join('categoria_producto', 'producto.id_producto', '=', 'categoria_producto.id_producto')
            ->join('categoria', 'categoria_producto.id_categoria', '=', 'categoria.id_categoria')
            ->join('venta_detalle_producto', 'producto.id_producto', '=', 'venta_detalle_producto.id_producto')
            ->join('venta', 'venta_detalle_producto.id_venta', '=', 'venta.id_venta')
            ->where(function ($query) {
                $query->where('venta.status', 'entregada')
                    ->orWhere('venta.status', 'pagada');
            })
            ->whereBetween('venta.fecha', [$from, $to]);

        $ofertas =
            DB::table('producto')
            ->select(
                'producto.id_producto',
                'producto.nombre',
                'marca.descripcion as marca',
                'color.descripcion as color',
                'categoria.descripcion as categoria',
                'venta_detalle_oferta.cantidad'
            )
            ->join('marca', 'producto.id_marca', '=', 'marca.id_marca')
            ->join('color', 'producto.id_color', '=', 'color.id_color', 'left outer')
            ->join('categoria_producto', 'producto.id_producto', '=', 'categoria_producto.id_producto')
            ->join('categoria', 'producto.id_producto', '=', 'categoria.id_categoria')
            ->join('producto_oferta', 'producto.id_producto', '=', 'producto_oferta.id_producto')
            ->join('venta_detalle_oferta', 'producto_oferta.id_oferta', '=', 'venta_detalle_oferta.id_oferta')
            ->join('venta', 'venta_detalle_oferta.id_venta', '=', 'venta.id_venta')
            ->where(function ($query) {
                $query->where('venta.status', 'entregada')
                    ->orWhere('venta.status', 'pagada');
            })
            ->whereBetween('venta.fecha', [$from, $to]);

        $kits = DB::table('venta_detalle_kit')
            ->select(
                'kit.nombre',
                'marca.descripcion as marca',
                'color.descripcion as color',
                'categoria.descripcion as categoria',
                DB::raw('SUM(venta_detalle_kit.cantidad) as cantidad')
            )
            ->join('kit', 'venta_detalle_kit.id_kit', '=', 'kit.id_kit')
            ->join('venta_kit_producto', 'venta_detalle_kit.id_detalle_kit', '=', 'venta_kit_producto.id_detalle_kit')
            ->join('kit_producto', 'kit_producto.id_kit_producto', '=', 'venta_kit_producto.id_kit_producto')
            ->join('producto', 'producto.id_producto', '=', 'kit_producto.id_producto')
            ->join('marca', 'producto.id_marca', '=', 'marca.id_marca')
            ->join('color', 'producto.id_color', '=', 'color.id_color', 'left outer')
            ->join('categoria', 'kit.id_categoria', '=', 'categoria.id_categoria')
            ->join('venta', 'venta_detalle_kit.id_venta', '=', 'venta.id_venta')
            ->where('kit_producto.cantidad', 1)
            ->where(function ($query) {
                $query->where('venta.status', 'entregada')
                    ->orWhere('venta.status', 'pagada');
            })
            ->whereBetween('venta.fecha', [$from, $to])
            ->groupBy(['kit.id_kit', 'color.id_color']);

        $unionProdOferta = $productos->unionAll($ofertas);

        $productoOfertas = DB::table(DB::raw("({$unionProdOferta->toSql()}) as unionProdOfertas"))
            ->select('nombre', 'marca', 'color', 'categoria', DB::raw('SUM(cantidad) as cantidad'))
            ->mergeBindings($unionProdOferta)
            ->groupBy(['id_producto']);

        $prodOfKits = $productoOfertas->union($kits);

        $allUnions = DB::table(DB::raw("({$prodOfKits->toSql()}) as allUnions"))
            ->select('nombre', 'marca', 'color', 'categoria', 'cantidad')
            ->mergeBindings($prodOfKits);

        return $this->applyScopes($allUnions);
    }`

- MAC OS Hig Sierra
- PHP 5.6.30
- Laravel 5.4
- Laravel-Datatables 7.0

**Comment by yajra** [comment]
It seems like you are using the wrong engine. Your query is a builder and not eloquent, thus you should use `->query()` instead of `->eloquent()`.

**Comment by warlof** [comment]
Hello there, sorry to bump that topic, but I'm involving in the same trouble.

My datatable is rendered over 5 subsequent tables due to polymorphic, merged using union.
I follow your sample here https://datatables.yajrabox.com/fluent/union - but it throw me an exception, attempting to call `getQuery()` on a **QueryBuilder** instead of an **EloquentBuilder**.

The complete class is available here https://github.com/warlof/seat-connector/blob/2.0.3/src/Http/DataTables/AccessDataTable.php

Here is the code I'm using to return the query :

```
    /**
     * @return \Illuminate\Database\Query\Builder
     */
    private function getCorporationQuery()
    {
        $query = Set::
            join('seat_connector_set_entity', 'set_id', 'id')
            ->join((new CorporationInfo())->getTable(), function ($join) {
                $join->on('entity_id', 'corporation_id');
                $join->where('entity_type', CorporationInfo::class);
            })
            ->select(
                'seat_connector_sets.id',
                'seat_connector_sets.connector_type',
                'seat_connector_sets.connector_id',
                'seat_connector_sets.name',
                'seat_connector_set_entity.entity_type',
                'seat_connector_set_entity.entity_id',
                (new CorporationInfo())->getTable() . '.name as entity_name')
            ->groupBy('id', 'connector_type', 'connector_id', 'name', 'entity_type', 'entity_id', 'entity_name');

        return $query;
    }

    /**
     * @return \Illuminate\Database\Query\Builder
     */
    private function getTitleQuery()
    {
        $query = Set::
            join('seat_connector_set_entity', 'set_id', 'seat_connector_sets.id')
            ->join((new CorporationTitle())->getTable(), function ($join) {
                $join->on('entity_id', (new CorporationTitle())->getTable() . '.id')
                    ->where('entity_type', CorporationTitle::class);
            })
            ->select(
                'seat_connector_sets.id',
                'seat_connector_sets.connector_type',
                'seat_connector_sets.connector_id',
                'seat_connector_sets.name',
                'seat_connector_set_entity.entity_type',
                'seat_connector_set_entity.entity_id',
                (new CorporationTitle())->getTable() . '.name as entity_name')
            ->groupBy('id', 'connector_type', 'connector_id', 'name', 'entity_type', 'entity_id', 'entity_name');

        return $query;
    }

    /**
     * @return \Illuminate\Database\Query\Builder
     */
    private function getAllianceQuery()
    {
        $query = Set::
            join('seat_connector_set_entity', 'set_id', 'id')
            ->join((new Alliance())->getTable(), function ($join) {
                $join->on('entity_id', 'alliance_id');
                $join->where('entity_type', Alliance::class);
            })
            ->select(
                'seat_connector_sets.id',
                'seat_connector_sets.connector_type',
                'seat_connector_sets.connector_id',
                'seat_connector_sets.name',
                'seat_connector_set_entity.entity_type',
                'seat_connector_set_entity.entity_id',
                (new Alliance())->getTable() . '.name as entity_name')
            ->groupBy('id', 'connector_type', 'connector_id', 'name', 'entity_type', 'entity_id', 'entity_name');

        return $query;
    }

    /**
     * @return \Illuminate\Database\Query\Builder
     */
    private function getRoleQuery()
    {
        $query = Set::
            join('seat_connector_set_entity', 'set_id', 'id')
            ->join((new Role())->getTable(), function ($join) {
                $join->on('entity_id', (new Role())->getTable() . '.id');
                $join->where('entity_type', Role::class);
            })
            ->select(
                'seat_connector_sets.id',
                'seat_connector_sets.connector_type',
                'seat_connector_sets.connector_id',
                'seat_connector_sets.name',
                'seat_connector_set_entity.entity_type',
                'seat_connector_set_entity.entity_id',
                (new Role())->getTable() . '.title as entity_name')
            ->groupBy('id', 'connector_type', 'connector_id', 'name', 'entity_type', 'entity_id', 'entity_name');

        return $query;
    }

    /**
     * @return \Illuminate\Database\Query\Builder
     */
    private function getUserQuery()
    {
        $query = Set::
            join('seat_connector_set_entity', 'set_id', 'id')
            ->join((new User())->getTable(), function ($join) {
                $join->on('entity_id', (new User())->getTable() . '.id');
                $join->where('entity_type', User::class);
            })
            ->select(
                'seat_connector_sets.id',
                'seat_connector_sets.connector_type',
                'seat_connector_sets.connector_id',
                'seat_connector_sets.name',
                'seat_connector_set_entity.entity_type',
                'seat_connector_set_entity.entity_id',
                (new User())->getTable() . '.name as entity_name')
            ->groupBy('id', 'connector_type', 'connector_id', 'name', 'entity_type', 'entity_id', 'entity_name');

        return $query;
    }

    /**
     * @return \Illuminate\Database\Query\Builder
     */
    private function getPublicQuery()
    {
        $query = Set::where('is_public', true)
            ->select(
                'seat_connector_sets.id',
                'seat_connector_sets.connector_type',
                'seat_connector_sets.connector_id',
                'seat_connector_sets.name'
            )
            ->selectRaw('? as entity_type, ? as entity_id, ? as entity_name', ['public', '0', ''])
            ->groupBy('id', 'connector_type', 'connector_id', 'name', 'entity_type', 'entity_id', 'entity_name');

        return $query;
    }
```

everything merged into

```
    /**
     * @return \Illuminate\Database\Query\Builder
     */
    public function query()
    {
        $corporation = $this->getCorporationQuery();
        $titles = $this->getTitleQuery();
        $alliances = $this->getAllianceQuery();
        $roles = $this->getRoleQuery();
        $users = $this->getUserQuery();
        $public = $this->getPublicQuery();

        $union = $corporation->union($titles)->union($alliances)->union($roles)->union($users)->union($public);

        return $this->applyScopes(DB::table(DB::raw("({$union->toSql()}) as mapping")));
    }
```

and here is the stack trace

```
[2020-04-11 17:46:08] local.ERROR: Call to undefined method Illuminate\Database\Query\Builder::getQuery() {"userId":260,"exception":"[object] (BadMethodCallException(code: 0): Call to undefined method Illuminate\\Database\\Query\\Builder::getQuery() at /var/www/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:50)
[stacktrace]
#0 /var/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3087): Illuminate\\Database\\Query\\Builder::throwBadMethodCallException('getQuery')
#1 /var/www/vendor/yajra/laravel-datatables-oracle/src/EloquentDataTable.php(37): Illuminate\\Database\\Query\\Builder->__call('getQuery', Array)
#2 /var/www/vendor/yajra/laravel-datatables-oracle/src/DataTableAbstract.php(167): Yajra\\DataTables\\EloquentDataTable->__construct(Object(Illuminate\\Database\\Query\\Builder))
#3 /var/www/vendor/yajra/laravel-datatables-oracle/src/DataTables.php(115): Yajra\\DataTables\\DataTableAbstract::create(Object(Illuminate\\Database\\Query\\Builder))
#4 /var/www/vendor/warlof/seat-connector/src/Http/DataTables/AccessDataTable.php(48): Yajra\\DataTables\\DataTables->eloquent(Object(Illuminate\\Database\\Query\\Builder))
#5 [internal function]: Warlof\\Seat\\Connector\\Http\\DataTables\\AccessDataTable->ajax()
#6 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#7 /var/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#9 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#10 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#11 /var/www/vendor/yajra/laravel-datatables-buttons/src/Services/DataTable.php(158): Illuminate\\Container\\Container->call(Array)
#12 /var/www/vendor/warlof/seat-connector/src/Http/Controllers/AccessController.php(81): Yajra\\DataTables\\Services\\DataTable->render('seat-connector:...')
#13 [internal function]: Warlof\\Seat\\Connector\\Http\\Controllers\\AccessController->index(Object(Warlof\\Seat\\Connector\\Http\\DataTables\\AccessDataTable))
#14 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#15 /var/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('index', Array)
#16 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Warlof\\Seat\\Connector\\Http\\Controllers\\AccessController), 'index')
#17 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#18 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#19 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /var/www/vendor/eveseat/web/src/Http/Middleware/Bouncer/Bouncer.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Seat\\Web\\Http\\Middleware\\Bouncer\\Bouncer->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'seat-connector....')
#22 /var/www/vendor/eveseat/web/src/Http/Middleware/Locale.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Seat\\Web\\Http\\Middleware\\Locale->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /var/www/vendor/eveseat/web/src/Http/Middleware/Authenticate.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Seat\\Web\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /var/www/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#40 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#41 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#42 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#43 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#44 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#45 /var/www/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#57 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#58 /var/www/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#59 {main}
"}
```
