### ISSUE TITLE
search and sort not working when using (->with()) in the query methode

### ISSUE THREAD

**Issue by moathOSA** [yajra/laravel-datatables#2833]
### Summary of problem or feature request
the problem is i follow all the solution that's provided to the same issue and applies every mentioned solution but i ended up with this error 

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'category.name' in 'where clause' (SQL: select count(*) as aggregate from `products`  . . .
```

### Code snippet of problem
query 
```
    public function query(Store $model): QueryBuilder
    {
        $model = $model->newQuery()->with(['products', 'products.category'])->first();

        return $model->products->toQuery();
    }

```
columns
```
protected function getColumns(): array
    {
        return [
            Column::make('name'),
            Column::make('category_id')
                ->data('category.name')
                ->name('category.name')
                ->title('category'),
        ];
    }

```
datatable
```
    public function dataTable($query)
    {
        return (new EloquentDataTable($query))
            ->editColumn('category.name', function ($query) {
                return $query->category->name;
            });
    }


```
### System details
- Laravel Version ^9.19
- Laravel-Datatables Version ^9.0

**Comment by patricTOB** [comment]
Hi @moathOSA,

Your query function is incorrect.

    public function query(Store $model): QueryBuilder
    {
        return $model->newQuery()->with(['products.category']);
    }

Please try this one.

**Comment by moathOSA** [comment]
@patricTOB 
i actually need to access the products too, that's why i have ->with(['products', 'products.category'])
i don't have a problem accessing products data or products.category data my only problem is the category name is not searchable or sortable

**Comment by moathOSA** [comment]
@patricTOB  
i tried the query that you motioned this is what i got in the laravel.log 
```
class Illuminate\Database\Eloquent\Builder could not be converted to string
```

**Comment by patricTOB** [comment]
I notice one incorrect part on the code I suggested to you.

The return type should be EloquentBuilder.

public function query(Store $model): EloquentBuilder
{
    return $model->newQuery()->with(['products.category']);
}

Could you share here's the whole stack trace? that would be helpful.

**Comment by moathOSA** [comment]
@patricTOB 

please note that i need to access data from products and data from category and the model injected to the query is for the Store
```
[2022-08-16 11:09:31] local.ERROR: ErrorException: Attempt to read property "name" on null in /app/DataTables/ProductsDataTable.php:25
Stack trace:
#0 /vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(257): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /app/DataTables/ProductsDataTable.php(25): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#2 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\DataTables\ProductsDataTable->App\DataTables\{closure}()
#3 /vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#4 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(81): Illuminate\Container\Util::unwrapIfClosure()
#5 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#6 /vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call()
#7 /vendor/yajra/laravel-datatables-oracle/src/Utilities/Helper.php(77): Illuminate\Container\Container->call()
#8 /vendor/yajra/laravel-datatables-oracle/src/Processors/DataProcessor.php(170): Yajra\DataTables\Utilities\Helper::compileContent()
#9 /vendor/yajra/laravel-datatables-oracle/src/Processors/DataProcessor.php(117): Yajra\DataTables\Processors\DataProcessor->editColumns()
#10 /vendor/yajra/laravel-datatables-oracle/src/DataTableAbstract.php(858): Yajra\DataTables\Processors\DataProcessor->process()
#11 /vendor/yajra/laravel-datatables-oracle/src/QueryDataTable.php(100): Yajra\DataTables\DataTableAbstract->processResults()
#12 /vendor/yajra/laravel-datatables-oracle/src/DataTableAbstract.php(679): Yajra\DataTables\QueryDataTable->make()
#13 /vendor/yajra/laravel-datatables-buttons/src/Services/DataTable.php(268): Yajra\DataTables\DataTableAbstract->toJson()
#14 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Yajra\DataTables\Services\DataTable->ajax()
#15 /vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#16 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#17 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#18 /vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call()
#19 /vendor/yajra/laravel-datatables-buttons/src/Services/DataTable.php(206): Illuminate\Container\Container->call()
#20 /app/Http/Controllers/ProductController.php(29): Yajra\DataTables\Services\DataTable->render()
#21 /vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\ProductController->index()
#22 /vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
#23 /vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\Routing\ControllerDispatcher->dispatch()
#24 /vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\Route->runController()
#25 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\Routing\Route->run()
#26 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#27 /vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#28 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#29 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#31 /vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#32 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#33 /vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#34 /vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#35 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle()
#36 /vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#37 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#38 /vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#39 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#40 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then()
#42 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Routing\Router->runRouteWithinStack()
#43 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\Routing\Router->runRoute()
#44 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\Routing\Router->dispatchToRoute()
#45 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\Routing\Router->dispatch()
#46 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#47 /vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#48 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle()
#49 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#50 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#51 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#52 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#53 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#54 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#55 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#56 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#57 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#58 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#59 /vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#60 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\HandleCors->handle()
#61 /vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#62 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies->handle()
#63 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#64 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then()
#65 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#66 /public/index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#67 /home/mawdoo3/.config/composer/vendor/cpriego/valet-linux/server.php(232): require('...')
#68 {main}  

```

**Comment by patricTOB** [comment]
Based on the stack trace there are 2 possible issues here.

1. you need to correct this column.
Column::make('category_id')
                ->data('products.category.name')
                ->name('products.category.name')
                ->title('category'),

2. I'm not sure if this name is defined on your Store model.
            Column::make('name'),

**Comment by moathOSA** [comment]
@patricTOB  well thanks Patric for the effort you do to help me , i really appreciate it, but actually what i do i changed the injected model and define the parent store using where condition and this solved my problem
