### ISSUE TITLE
issue on Filtering Datatable implemented as service

### ISSUE THREAD

**Issue by jopi2016** [yajra/laravel-datatables#414]
Hi,
I've got a problem on filtering a datatable. (The query is a join of 2 tables).
My query to get the complete data is the following:
```php
        $users = User::select('users.id AS usersid', 'users.name AS usersname', 'users.email AS usersemail', 'users.department AS usersdepartment', 'users.userrole_id AS usersuserrole_id', 'users.is_active_id AS usersis_active_id', 'users.created_at AS userscreated_at', 'users.updated_at AS usersupdated_at', 'userroles.role AS userrolesrole')->join('userroles', 'userroles.userrole2_id', '=', 'users.userrole_id');
```
All the data are displayed correctly.

But when I try to search in the datatable I get the following error:
The problem seems to bee that in the select count() the AS definitions aren't contained but just a * is used.

```
Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'usersid' in 'where clause' (SQL: select count(*) as aggregate from (select '1' as `row_count` from `users` inner join `userroles` on `userroles`.`userrole2_id` = `users`.`userrole_id` where (LOWER(`usersid`) LIKE %o% or LOWER(`usersname`) LIKE %o% or LOWER(`usersemail`) LIKE %o% or LOWER(`usersdepartment`) LIKE %o% or LOWER(`userrolesrole`) LIKE %o% or LOWER(`userscreated_at`) LIKE %o% or LOWER(`usersupdated_at`) LIKE %o%)) count_row_table) in /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Database/Connection.php:670
Stack trace:
#0 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Database/Connection.php(630): Illuminate\Database\Connection->runQueryCallback('select count(*)...', Array, Object(Closure))
#1 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Database/Connection.php(343): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#2 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1461): Illuminate\Database\Connection->select('select count(*)...', Array, true)
#3 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1447): Illuminate\Database\Query\Builder->runSelect()
#4 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1808): Illuminate\Database\Query\Builder->get(Array)
#5 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1728): Illuminate\Database\Query\Builder->aggregate('count', Array)
#6 /home/vagrant/Code/laravel_datatables/vendor/yajra/laravel-datatables-oracle/src/Engines/QueryBuilderEngine.php(93): Illuminate\Database\Query\Builder->count()
#7 /home/vagrant/Code/laravel_datatables/vendor/yajra/laravel-datatables-oracle/src/Engines/BaseEngine.php(580): Yajra\Datatables\Engines\QueryBuilderEngine->count()
#8 /home/vagrant/Code/laravel_datatables/vendor/yajra/laravel-datatables-oracle/src/Engines/BaseEngine.php(543): Yajra\Datatables\Engines\BaseEngine->filterRecords()
#9 /home/vagrant/Code/laravel_datatables/vendor/yajra/laravel-datatables-oracle/src/Engines/QueryBuilderEngine.php(66): Yajra\Datatables\Engines\BaseEngine->make(true, false)
#10 /home/vagrant/Code/laravel_datatables/app/Datatables/UsersDataTable.php(22): Yajra\Datatables\Engines\QueryBuilderEngine->make(true)
#11 /home/vagrant/Code/laravel_datatables/vendor/yajra/laravel-datatables-oracle/src/Services/DataTable.php(84): prt\DataTables\UsersDataTable->ajax()
#12 /home/vagrant/Code/laravel_datatables/app/Http/Controllers/UsersController.php(32): Yajra\Datatables\Services\DataTable->render('users.index')
#13 [internal function]: prt\Http\Controllers\UsersController->index(Object(prt\DataTables\UsersDataTable))
#14 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(76): call_user_func_array(Array, Array)
#15 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction('index', Array)
#16 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call(Object(prt\Http\Controllers\UsersController), Object(Illuminate\Routing\Route), 'index')
#17 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 /home/vagrant/Code/laravel_datatables/app/Http/Middleware/Authenticate.php(28): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 [internal function]: prt\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#22 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#27 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(prt\Http\Controllers\UsersController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#28 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Routing/Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'prt\\Http\\Contro...', 'index')
#29 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Routing/Route.php(140): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#30 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#41 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#43 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#46 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#48 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#51 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#53 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#56 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#58 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#60 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Routing/Router.php(705): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#61 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Routing/Router.php(678): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#62 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Routing/Router.php(654): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#63 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(282): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#64 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#65 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#66 /home/vagrant/Code/laravel_datatables/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#67 [internal function]: Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#68 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#69 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#70 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#71 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#72 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#73 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#74 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#76 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#77 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#78 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#79 /home/vagrant/Code/laravel_datatables/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#80 /home/vagrant/Code/laravel_datatables/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#81 {main}  

The 2 tables were created the following way:
CREATE TABLE `userroles` (
  `userrole2_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `role` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `created2_at` timestamp NULL DEFAULT NULL,
  `updated2_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`userrole2_id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `department` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `userrole_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(60) COLLATE utf8_unicode_ci NOT NULL,
  `is_active_id` int(11) NOT NULL,
  `remember_token` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `is_admin` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=1883 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

Any ideas?

**Comment by yajra** [comment]
Can you please paste your javascript?

**Comment by yajra** [comment]
Whoops! Implemented via service. Can you rather please paste your `html()` method? Since you use an alias, you need to declare your columns to something like below:

```php
public function html()
{
    return $this->builder()
                ->columns($this->getColumns())
                ->ajax('')
                ->addAction(['width' => '134px'])
                ->parameters($this->getBuilderParameters());
}

private function getColumns()
{
    return [
        'id'   => ['data' => 'usersid', 'name' => 'users.id'],
        'name' => ['data' => 'usersname', 'name' => 'users.name']
    ];
}
```

See this [demo](http://datatables.yajrabox.com/eloquent/joins) for reference on how to declare your columns when using join statements.

**Comment by jopi2016** [comment]
awesome, that worked. Thanks
